services:
  api:
    image: ghcr.io/brindhakavinkumar/orders_app:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: orders_user
      DB_PASSWORD: orders_pass
      DB_NAME: orders_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: orders_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
